apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterdrill-web
  namespace: clusterdrill-system
  labels:
    {{- include "clusterdrill.labels" . | nindent 4 }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/component: web
automountServiceAccountToken: true
